application:
  port: 8000
  host: 0.0.0.0
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "zero2axum"
email_client: 
  base_url: "https://api.postmarkapp.com"
  sender_email: "brian@kitazon.com"
